// uva.js — Hybrid UVA irradiance model.
//
// We cannot fetch "pure UVA" from a free API (every weather API serves the
// erythemally-weighted UV Index, which is mostly UVB). So we DERIVE UVA
// (unweighted, 315-400 nm, in W/m2) from:
//   1. a clear-sky radiative-transfer lookup table (js/lut.js, generated by
//      scripts/build_lut.py with the DISORT solver) indexed by sun angle,
//      aerosol optical depth and surface pressure;
//   2. surface reflection, from the table's atmospheric spherical albedo;
//   3. the Earth-Sun distance on the day;
//   4. cloud, from live data.
//
// Total-column ozone is held at 300 DU in the table: it absorbs mostly UVB
// and barely touches UVA, and the free data source only offers surface ozone.
//
// The tunable coefficients that remain live in MODEL so they can be
// calibrated against reference data (scripts/validate.mjs). Functions are
// pure.

import { ZENITH, AOD, PRESSURE, UVA, SPHERICAL_ALBEDO } from './lut.js';

export const MODEL = {
  // Cloud transmission (fallback, parametric): factor = 1 - CLOUD_K * (cover/100)^CLOUD_EXP.
  // Used only when we can't derive the cloud effect from live UV data. Tuned to
  // be gentle and gradual — a reported "100% cover" is sky coverage, not optical
  // depth, so the average overcast UVA transmission is moderate (~0.6), not the
  // near-blackout a steep curve produces.
  CLOUD_K: 0.4,
  CLOUD_EXP: 1.5,

  // When we know the erythemal (UV Index) cloud transmission T_uv — from live
  // uv_index / uv_index_clear_sky — UVA's is taken as T_uva = T_uv ^ CLOUD_UVA_EXP.
  // Spectral measurements under cloud find UVA and erythemal transmission
  // close to each other (if anything the shorter wavelengths get through
  // slightly better, from extra scattering between cloud and the air above),
  // so the neutral value 1 is used until scripts/validate.mjs says otherwise.
  CLOUD_UVA_EXP: 1.0,

  // UV albedo of the SURROUNDINGS (the kilometre-scale area around you, not
  // just the ground underfoot): it sets how much reflected light the sky
  // sends back down onto a horizontal surface. Typical values in the UVA.
  ALBEDO: {
    grass: 0.03, // vegetation, soil, most towns
    water: 0.07, // open water, sun well up
    sand: 0.15, // dry sand / beach
    snow: 0.6, // snow-covered terrain (fresh snow alone reaches ~0.9)
  },

  // Snow depth (m, from the forecast) above which "Auto" surroundings count
  // as snow-covered.
  SNOW_DEPTH_M: 0.05,

  // UVA Index scale: divisor turning UVA irradiance (W/m2) into a clean 0-11+
  // index, so clear-sky overhead sun (~64-66 W/m2 at sea level) maps to ~11 —
  // the same top-of-scale feel as the erythemal UV Index (which scales its
  // irradiance by x40). One constant, strictly proportional to the real
  // irradiance, so the index is easy to explain and to recalibrate.
  INDEX_DIVISOR: 6,
};

// Sea-level standard pressure, hPa.
export const P0 = 1013.25;

// Convert UVA irradiance (W/m2) to the dimensionless UVA Index (0-11+).
export function uvaIndex(uva, model = MODEL) {
  return uva / model.INDEX_DIVISOR;
}

// Standard-atmosphere surface pressure (hPa) for an elevation (m) — the
// fallback when the forecast has no pressure.
export function pressureFromElevation(elevationM) {
  return P0 * Math.pow(1 - 2.25577e-5 * elevationM, 5.25588);
}

// Locate `x` on an ascending grid: [index of the lower node, fraction].
// Values outside the grid are clamped to its ends.
function bracket(grid, x) {
  if (!(x > grid[0])) return [0, 0];
  const last = grid.length - 1;
  if (x >= grid[last]) return [last - 1, 1];
  let i = 0;
  while (grid[i + 1] < x) i++;
  return [i, (x - grid[i]) / (grid[i + 1] - grid[i])];
}

const lerp = (a, b, t) => a + (b - a) * t;

// Clear-sky global horizontal UVA (W/m2) over a black surface at 1 AU, by
// trilinear interpolation of the radiative-transfer table.
export function clearSkyUVA(zenith, aod, pressureHpa) {
  const [i, ti] = bracket(ZENITH, zenith);
  const [j, tj] = bracket(AOD, aod);
  const [k, tk] = bracket(PRESSURE, pressureHpa);
  const at = (z, a) => lerp(UVA[z][a][k], UVA[z][a][k + 1], tk);
  const atZ = (z) => lerp(at(z, j), at(z, j + 1), tj);
  return Math.max(0, lerp(atZ(i), atZ(i + 1), ti));
}

// The atmosphere's spherical albedo s (bilinear), for surface reflection:
// a Lambertian surface of albedo r multiplies the irradiance by 1 / (1 - r*s).
export function sphericalAlbedo(aod, pressureHpa) {
  const [j, tj] = bracket(AOD, aod);
  const [k, tk] = bracket(PRESSURE, pressureHpa);
  const at = (a) => lerp(SPHERICAL_ALBEDO[a][k], SPHERICAL_ALBEDO[a][k + 1], tk);
  return lerp(at(j), at(j + 1), tj);
}

// Compute UVA. `inputs` fields:
//   zenith        (deg, required)
//   aboveHorizon  (bool, required)
//   pressureHpa   (surface pressure, hPa; preferred — sets the air column)
//   elevationM    (m; used only when pressureHpa is missing)
//   aod           (aerosol optical depth at 550 nm, optional — 0 if missing)
//   distanceAU    (Earth-Sun distance, AU, default 1)
//   cloudCover    (% 0-100, optional — parametric cloud fallback)
//   uvCloudTransmission (0-1, optional — erythemal cloud transmission derived
//                  from live uv_index / uv_index_clear_sky; preferred over
//                  cloudCover because it reflects the real sky)
//   albedo        (surroundings' UV albedo 0-1), or
//   surface       ('grass'|'water'|'sand'|'snow', default 'grass')
//
// Returns { uva, index, band, factors } where `factors` itemizes each
// multiplier so the UI can show a transparent breakdown; their product is
// the result.
export function computeUVA(inputs, model = MODEL) {
  const {
    zenith,
    aboveHorizon,
    pressureHpa,
    elevationM = 0,
    aod,
    distanceAU = 1,
    cloudCover,
    uvCloudTransmission,
    surface = 'grass',
  } = inputs;

  if (!aboveHorizon || zenith >= 90) {
    return {
      uva: 0,
      index: 0,
      band: classifyUVA(0),
      factors: { baseline: 0, note: 'Sun below horizon' },
    };
  }

  const p = isFinite(pressureHpa) && pressureHpa > 0 ? pressureHpa : pressureFromElevation(elevationM);
  const tau = isFinite(aod) && aod > 0 ? aod : 0;

  // 1. Clear-sky baseline: clean air, sea level, black surface, 1 AU.
  const baseline = clearSkyUVA(zenith, 0, P0);
  const ratio = (a, b) => (b > 0 ? a / b : 1);

  // 2. Altitude: a thinner air column above (less Rayleigh scattering out).
  const cleanAtSite = clearSkyUVA(zenith, 0, p);
  const altitudeFactor = ratio(cleanAtSite, baseline);

  // 3. Aerosol: the table's full multiple-scattering answer for this haze,
  //    relative to clean air — so haze is never counted twice.
  const aerosolFactor = ratio(clearSkyUVA(zenith, tau, p), cleanAtSite);

  // 4. Surface reflection bouncing back down off the sky.
  const albedo = inputs.albedo ?? model.ALBEDO[surface] ?? model.ALBEDO.grass;
  const albedoFactor = 1 / (1 - albedo * sphericalAlbedo(tau, p));

  // 5. Earth-Sun distance: +/-3.3% over the year (closest in early January).
  const distanceFactor = 1 / (distanceAU * distanceAU);

  // 6. Cloud. Prefer the live-UV-derived transmission (real sky); otherwise
  //    fall back to the parametric cloud-cover curve.
  let cloudFactor = 1;
  if (typeof uvCloudTransmission === 'number' && isFinite(uvCloudTransmission)) {
    const tUv = Math.min(1, Math.max(0, uvCloudTransmission));
    cloudFactor = Math.pow(tUv, model.CLOUD_UVA_EXP);
  } else if (typeof cloudCover === 'number') {
    const c = Math.min(100, Math.max(0, cloudCover)) / 100;
    cloudFactor = 1 - model.CLOUD_K * Math.pow(c, model.CLOUD_EXP);
  }

  const uva =
    baseline * altitudeFactor * aerosolFactor * albedoFactor * distanceFactor * cloudFactor;

  const value = Math.max(0, uva);
  const index = uvaIndex(value, model);

  return {
    uva: value,
    index,
    band: classifyUVA(index),
    factors: {
      baseline,
      altitude: altitudeFactor,
      aerosol: aerosolFactor,
      albedo: albedoFactor,
      distance: distanceFactor,
      cloud: cloudFactor,
    },
    pressureHpa: p,
    albedo,
  };
}

// Qualitative bands for the UVA Index (0-11+). The category boundaries
// deliberately reuse the WHO UV Index bands (Low 0-2, Moderate 3-5, High 6-7,
// Very High 8-10, Extreme 11+) so the scale is instantly familiar — only the
// underlying quantity (unweighted UVA, not erythemal UV) differs. `from` is
// the band's lower bound; it runs up to the next band's `from`.
export const BANDS = [
  { label: 'Low', level: 0, from: 0, color: '#3a7d44' },
  { label: 'Moderate', level: 1, from: 3, color: '#f2c14e' },
  { label: 'High', level: 2, from: 6, color: '#f08a24' },
  { label: 'Very High', level: 3, from: 8, color: '#e3522f' },
  { label: 'Extreme', level: 4, from: 11, color: '#b5179e' },
];

// Band for a UVA Index value.
export function classifyUVA(index) {
  let band = BANDS[0];
  for (const b of BANDS) if (index >= b.from) band = b;
  const { label, level, color } = band;
  return { label, level, color };
}
